title: dr-jekyll
description: "A small Jekyll theme made for YSWS Hack Club - minimalist or something like that"
encoding: utf-8

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]